#
# configraiton for avatar instance
#

instance_name: 'stepladder'

zmq:
  heartbeat:
    update_interval_hz: 50
    dst:
      - 'tcp://10.110.40.200:5001'
  teleop:
    src:
      - 'tcp://10.110.40.200:5000'
      - 'tcp://10.100.10.82:5000'
      - 'ipc:///tmp/avatar/teleop'

inputs:
  0:
    name: 'limit_sw_1'
    connection: 'gpio'
    address: 17
    params:
      mode: 'pulldown'
      # event_actuation: 'CCW'
      # condition: 'HIGH'
  1:
    name: 'limit_sw_2'
    connection: 'gpio'
    address: 18
    params:
      mode: 'pulldown'
      # event_actuation: 'CW'
      # condition: 'HIGH'
  # 2:
  #   name: 'max_sonar_tty'
  #   connection: 'serial'
  #   address: '/dev/ttyS0'
  #   params:
  #     emergency_stop_threshold_mm: 500
  #     sampling_rate_hz: 20

outputs:
  0:
    driver:
      type: 'adafruit_motor_hat'
      connection: 'i2c'
      address: 0x60
    name: 'stepper 1'
    pin: 1
    type: 'stepper'
    params:
      steps: 200
      speed:
        max: 90 # rpm
        min: 0
      mode: 'DOUBLE' # SINGLE , DOUBLE , INTERLEAVE , MICROSTEP

actuation_map:
  # YAML format
  # 'FUNCTION_NAME':
  #   OUTPUT_INDEX: 'param:wait_ms param:wait_ms param:wait_ms ...'
  CW:
      # speed, steps, wait_ms ....
      # 0: '%d, -20, 0, 0, 0, 0' # stop every time
      0: '%d, -50, 0'
      forced_exec: False
  CCW:
      # 0: '%d, 20, 0, 0, 0, 0' # stop every time
      0: '%d, 50, 0'
      forced_exec: False
  STOP:
      0: '0, 0, 0'
      forced_exec: True
